/**
 * Gemma 4 26B Language Intelligence & AI Disaster Speech Interpreter
 * 
 * IMPORTANT: This module is the INTERPRETER, not the speech recognition engine.
 * The Speech-to-Text (ASR) service produces the transcript (Stage 2).
 * This module (Gemma 26B) interprets the transcript to extract structured emergency facts (Stage 4+).
 * 
 * Pipeline Position: Audio → STT → Language Detection → Transcript Normalization → Gemma 4 26B Analysis
 * 
 * Gemma 26B extracts these 8 structured parameters from the transcript:
 * 1. emergencyType    - Flood | Fire | Medical | Building Collapse | etc.
 * 2. severity         - LOW | MODERATE | HIGH | CRITICAL
 * 3. peopleAffected   - Integer count of people affected
 * 4. injuries         - Description of injuries mentioned
 * 5. trappedPeople    - Array of trapped person descriptions
 * 6. immediateHazards - Array of immediate hazard threats
 * 7. vulnerablePeople  - Array of vulnerable persons (elderly, children, etc.)
 * 8. locationClues    - Landmarks, street names, or location clues
 * 
 * Never fabricates missing information. Returns confidence scores.
 */

const gemmaClient = require('./gemmaClient');
const responseParser = require('./responseParser');
const logger = require('../../utils/logger');

const gemmaConfig = require('../../config/gemma');

/**
 * Formats prompt for Gemma 4 26B Multilingual Speech Intelligence Interpretation
 * @param {string} transcript
 * @returns {string} Formatted prompt string
 */
function buildAiDisasterIntelligencePrompt(transcript) {
  const cleanTranscript = (transcript || '').trim();

  return `You are Gemma 4 26B Emergency Speech Intelligence Interpreter for RESONIX AI.

IMPORTANT: You are interpreting a transcript generated by the Speech-To-Text (ASR) engine. You are NOT the speech recognition engine itself.

Analyze the voice transcript below and extract structured emergency facts.

GROUNDING & TRUTH RULES (MANDATORY):
1. Extract ONLY facts explicitly stated or clearly implied in the transcript.
2. If a detail is NOT mentioned in the transcript, use null or [] or "None reported" — NEVER invent facts.
3. The transcript may be in any language (Hindi, Tamil, Telugu, Kannada, Malayalam, Bengali, Gujarati, Marathi, English, or code-mixed like Hinglish/Tanglish).
4. Do NOT overwrite or replace the original transcript text with AI summary.

Transcript:
"${cleanTranscript}"

Return ONLY valid JSON matching this exact schema:
{
  "language": "Detected language (e.g. Tamil, Hindi, English, Tanglish, Hinglish)",
  "translationRequired": false,
  "originalText": "${cleanTranscript}",
  "englishTranslation": "English translation if required, or original text if already English",
  "emergencyType": "Flood | Fire | Medical | Building Collapse | Storm | Earthquake | Cyclone | Road Accident | Landslide | General",
  "severity": "LOW | MODERATE | HIGH | CRITICAL",
  "peopleAffected": 0,
  "injuries": "Description of injuries mentioned or None reported",
  "trappedPeople": ["Description or count of trapped people mentioned or []"],
  "immediateHazards": ["Hazards mentioned in transcript or []"],
  "vulnerablePeople": ["Vulnerable persons mentioned like elderly or children or []"],
  "locationClues": "Landmarks, street names, or location clues mentioned or Unknown",
  "responderBriefing": "Factual 1-2 sentence emergency briefing based strictly on transcript evidence",
  "summary": "Factual 1-2 sentence summary based strictly on transcript evidence",
  "recommendedAction": "Recommended immediate action for first response team"
}`;
}

/**
 * Interprets emergency voice transcript through Gemma 4 26B (via active AI provider)
 * IMPORTANT: This is transcript INTERPRETATION, not speech recognition.
 * The original transcript from the STT engine is preserved verbatim.
 * @param {Object} payload { transcript }
 * @returns {Promise<Object>} Structured emergency intelligence with 8 extracted parameters + confidence
 */
async function processLanguageIntelligence({ transcript = '' }, options = {}) {
  const inputTranscript = (typeof transcript === 'string' ? transcript : '').trim();
  const languageDetectionService = require('../pipeline/languageDetectionService');
  const langInfo = languageDetectionService.detect({ transcript: inputTranscript });

  if (!inputTranscript || langInfo.isUnknown) {
    return {
      language: langInfo.detectedLanguage || 'unknown',
      detectedLanguage: langInfo.detectedLanguage || 'unknown',
      originalTranscript: inputTranscript,
      normalizedTranscript: langInfo.normalizedTranscript || inputTranscript,
      translationRequired: false,
      originalText: inputTranscript,
      englishTranslation: '',
      englishText: '',
      incidentType: 'General',
      priority: 'LOW',
      numberOfPeople: 0,
      peopleAffected: 0,
      injuries: 'None reported',
      location: 'Unknown',
      locationMentioned: 'Unknown',
      hazards: [],
      weather: 'Weather data unavailable',
      infrastructureDamage: 'None reported',
      responderBriefing: inputTranscript ? 'Speech analysis inconclusive.' : 'No voice transcript provided.',
      summary: inputTranscript ? 'Speech analysis inconclusive.' : 'No voice transcript provided.',
      recommendedAction: 'Verify citizen situation directly.',
      gemmaModel: gemmaConfig.gemmaModel || 'gemma-4-26b-a4b-it',
      aiAvailable: true,
      speechIntelligenceSource: 'GEMMA_26B_TRANSCRIPT_INTERPRETER',
      sttEngine: 'SEPARATE_ASR_SERVICE',
    };
  }

  const prompt = buildAiDisasterIntelligencePrompt(langInfo.normalizedTranscript || inputTranscript);

  try {
    const activeModel = gemmaConfig.gemmaModel || 'gemma-4-26b-a4b-it';
    logger.info(`[GemmaDisasterIntelligence] Sending STT transcript to Gemma 4 26B [${gemmaConfig.provider}/${activeModel}] for interpretation (${inputTranscript.length} chars, Lang: ${langInfo.detectedLanguage})`);

    const result = await gemmaClient.generateJson(prompt, {
      parameters: {
        temperature: 0.1,
      },
      timeoutMs: options.timeoutMs || 30000,
      maxRetries: options.maxRetries || 1,
    });

    const rawOutput = result?.generated_text || result?.response || result?.text || '';

    const fallbackJson = {
      language: langInfo.detectedLanguage || null,
      translationRequired: langInfo.isMultilingual,
      originalText: inputTranscript,
      englishTranslation: inputTranscript,
      englishText: inputTranscript,
      incidentType: 'General',
      priority: 'HIGH',
      numberOfPeople: 0,
      peopleAffected: 0,
      injuries: 'None reported',
      location: 'Unknown',
      locationMentioned: 'Unknown',
      hazards: [],
      weather: 'Weather data unavailable',
      infrastructureDamage: 'Under Assessment',
      responderBriefing: inputTranscript,
      summary: inputTranscript,
      recommendedAction: 'Dispatch first responders to citizen coordinates',
    };

    const parsedJson = responseParser.parseJson(rawOutput, fallbackJson);

    const detectedLang = parsedJson.language || langInfo.detectedLanguage || 'unknown';
    const translatedText = parsedJson.englishTranslation || parsedJson.englishText || inputTranscript;
    const peopleCount = typeof parsedJson.numberOfPeople === 'number'
      ? parsedJson.numberOfPeople
      : typeof parsedJson.peopleAffected === 'number'
      ? parsedJson.peopleAffected
      : parseInt(parsedJson.numberOfPeople || parsedJson.peopleAffected, 10) || 0;
    const briefing = parsedJson.responderBriefing || parsedJson.summary || inputTranscript;

    const explainability = {
      detectedLanguage: detectedLang || null,
      languageReason: parsedJson.languageReason || (detectedLang ? `Detected script signatures and speech patterns for ${detectedLang}` : null),
      category: parsedJson.incidentType || null,
      categoryReason: parsedJson.categoryReason || (parsedJson.incidentType ? `Transcript indicates ${parsedJson.incidentType} hazard conditions` : null),
      severity: (parsedJson.priority || 'HIGH').toUpperCase(),
      severityReason: parsedJson.priorityReason || (parsedJson.priority ? `Classified as ${parsedJson.priority} based on victim density and situation urgency` : null),
      keyPhrases: Array.isArray(parsedJson.keyPhrases) ? parsedJson.keyPhrases : (parsedJson.keyPhrases ? [parsedJson.keyPhrases] : []),
      hazards: Array.isArray(parsedJson.hazards) ? parsedJson.hazards : (parsedJson.hazards ? [parsedJson.hazards] : []),
      peopleAffected: peopleCount > 0 ? peopleCount : null,
      translation: translatedText !== inputTranscript ? translatedText : null,
      recommendedResources: Array.isArray(parsedJson.recommendedResources) ? parsedJson.recommendedResources.join(', ') : (parsedJson.recommendedResources || null),
      confidence: typeof parsedJson.confidenceScore === 'number' ? parsedJson.confidenceScore : null,
    };

    // Phase 5: Extract 8 structured speech intelligence parameters
    const trappedPeople = Array.isArray(parsedJson.trappedPeople)
      ? parsedJson.trappedPeople
      : (parsedJson.trappedPeople ? [parsedJson.trappedPeople] : []);
    const immediateHazards = Array.isArray(parsedJson.immediateHazards)
      ? parsedJson.immediateHazards
      : Array.isArray(parsedJson.hazards)
      ? parsedJson.hazards
      : (parsedJson.hazards ? [parsedJson.hazards] : []);
    const vulnerablePeople = Array.isArray(parsedJson.vulnerablePeople)
      ? parsedJson.vulnerablePeople
      : (parsedJson.vulnerablePeople ? [parsedJson.vulnerablePeople] : []);
    const locationClues = parsedJson.locationClues || parsedJson.location || parsedJson.locationMentioned || 'Unknown';

    return {
      language: detectedLang,
      detectedLanguage: detectedLang,
      originalTranscript: inputTranscript,
      normalizedTranscript: langInfo.normalizedTranscript || inputTranscript,
      translationRequired: Boolean(parsedJson.translationRequired),
      originalText: parsedJson.originalText || inputTranscript,
      englishTranslation: translatedText,
      englishText: translatedText,
      // Phase 5: 8 Structured Speech Intelligence Parameters
      emergencyType: parsedJson.emergencyType || parsedJson.incidentType || 'General',
      severity: (parsedJson.severity || parsedJson.priority || 'HIGH').toUpperCase(),
      peopleAffected: peopleCount,
      injuries: parsedJson.injuries || 'None reported',
      trappedPeople,
      immediateHazards,
      vulnerablePeople,
      locationClues,
      // Legacy compatibility fields
      incidentType: parsedJson.incidentType || parsedJson.emergencyType || 'General',
      priority: (parsedJson.priority || parsedJson.severity || 'HIGH').toUpperCase(),
      numberOfPeople: peopleCount,
      location: parsedJson.location || parsedJson.locationMentioned || locationClues,
      locationMentioned: parsedJson.locationMentioned || parsedJson.location || locationClues,
      hazards: immediateHazards,
      weather: parsedJson.weather && parsedJson.weather !== 'Clear' && parsedJson.weather !== 'Unknown' ? parsedJson.weather : 'Weather data unavailable',
      infrastructureDamage: parsedJson.infrastructureDamage || 'None reported',
      responderBriefing: briefing,
      summary: briefing,
      recommendedAction: parsedJson.recommendedAction || 'Dispatch emergency response team to location',
      explainability,
      gemmaModel: gemmaConfig.gemmaModel || 'gemma-4-26b-a4b-it',
      aiAvailable: !result?.error,
      speechIntelligenceSource: 'GEMMA_26B_TRANSCRIPT_INTERPRETER',
      sttEngine: 'SEPARATE_ASR_SERVICE',
    };
  } catch (error) {
    logger.warn('[GemmaDisasterIntelligence] Gemma inference error:', error.message);
    return {
      language: 'English',
      translationRequired: false,
      originalText: inputTranscript,
      englishTranslation: inputTranscript,
      englishText: inputTranscript,
      incidentType: 'General',
      priority: 'HIGH',
      numberOfPeople: 0,
      peopleAffected: 0,
      injuries: 'None reported',
      location: 'Unknown',
      locationMentioned: 'Unknown',
      hazards: [],
      weather: 'Weather data unavailable',
      infrastructureDamage: 'None reported',
      responderBriefing: inputTranscript,
      summary: inputTranscript,
      recommendedAction: 'Dispatch emergency team to location.',
      gemmaModel: gemmaConfig.gemmaModel || 'gemma-4-26b-a4b-it',
      aiAvailable: false,
      speechIntelligenceSource: 'GEMMA_26B_TRANSCRIPT_INTERPRETER',
      sttEngine: 'SEPARATE_ASR_SERVICE',
    };
  }
}

module.exports = {
  processLanguageIntelligence,
  buildAiDisasterIntelligencePrompt,
};
