/**
 * Route Definitions & Registry for RESONIX AI Frontend
 */

export const ROUTES = {
  HOME: '/',
  LANGUAGE_SELECTION: '/language-selection',
  PERMISSIONS: '/permissions',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  REFINED_DASHBOARD: '/dashboard/refined',
  PREDICTIVE_DASHBOARD: '/dashboard/predictive',
  MAP: '/map',
  MAP_SIGNALS: '/map/signals',
  INTELLIGENCE: '/intelligence',
  INTELLIGENCE_MAP: '/intelligence/map',
  INTELLIGENCE_PERSONNEL: '/intelligence/personnel',
  INCIDENT: '/incident',
  PERSONNEL: '/personnel',
  PERSONNEL_DATA: '/personnel/data',
  PERSONNEL_DRILLDOWN: '/personnel/drilldown',
  LOGISTICS: '/logistics',
  LOGISTICS_ALERTS: '/logistics/alerts',
  LOGISTICS_GEO: '/logistics/geo',
  LOGISTICS_DEPLOYMENT: '/logistics/deployment',
  LOGISTICS_PREDICTIVE: '/logistics/predictive',
  DIAGNOSTICS: '/diagnostics',
  ANALYTICS: '/analytics',
  RESPONDER: '/responder',
  VOICE_RELAY: '/voice-relay',
  VOICE_EMERGENCY: '/voice-emergency',
  CRISIS_LOG: '/crisis-log',
  CRISIS_LOG_PREDICTIVE: '/crisis-log/predictive',
  SOS: '/citizen/sos',
  CITIZEN_SOS: '/citizen/sos',
  CITIZEN: '/citizen',
  OFFLINE_RELAY: '/offline-relay',
  GEMMA_PROCESSING: '/gemma-processing',
  EMERGENCY_GUIDE: '/emergency-guide',
  SETTINGS: '/citizen/settings',
};
